// Pages that set their own `openGraph` metadata replace the inherited one, including the
// image generated by app/opengraph-image.tsx, so they must reference it explicitly.
export const shareImage = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: "Skandiora Immigration — education guidance from Kochi, Trivandrum and Chennai",
};

export function shareMetadata(title: string, description: string, url?: string) {
  return {
    openGraph: { title, description, ...(url ? { url } : {}), type: "website" as const, images: [shareImage] },
    twitter: { card: "summary_large_image" as const, title, description, images: [shareImage.url] },
  };
}
